### Урок 2. Вычисления с помощью Numpy. Видеоурок


#### Задание 1
##### Импортируйте библиотеку Numpy и дайте ей псевдоним np.
##### Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
##### Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
##### Будем считать, что каждый столбец - это признак, а строка - наблюдение.
##### Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
##### Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [17]:
import numpy as np

a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).transpose()

mean_a = np.array([np.mean(a, axis=0)])

# print(f'\nКоличество измерений матрицы a : {a.ndim}')
print(f'\nМатрица а : \n{a}')

# print(f'\nКоличество измерений матрицы mean_a : {mean_a.ndim}')
print(f'\nМатрица mean_a : \n{mean_a}')


Матрица а : 
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]

Матрица mean_a : 
[[2.  8.4]]



#### Задание 2
##### Вычислите массив a_centered, отняв от значений массива а 
##### средние значения соответствующих признаков, содержащиеся в массиве mean_a.
##### Вычисление должно производиться в одно действие.
##### Получившийся массив должен иметь размер 5x2.

In [13]:
# Применяем  broadcasting
a_centered = a - mean_a

print(f'\nМатрица a_centered : \n{a_centered}')



Матрица a_centered : 
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]



#### Задание 3
##### Найдите скалярное произведение столбцов массива a_centered.
##### В результате должна получиться величина a_centered_sp. 
##### Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [14]:
col_1 = a_centered[:, 0]
col_2 = a_centered[:, 1]

print(f'\nПервый вектор скалярного произведения : {col_1}')
print(f'\nВторой вектор скалярного произведения : {col_2}')

a_centered_sp = np.dot(col_1,col_2)

print(f'\nСкалярное произведение столбцов матрицы a_centered : {a_centered_sp}')

print(f'\nСкалярное произведение столбцов матрицы a_centered' 
      f'\nподелнное на количество измерений N (кол-во строк матрицы a)'
      f'\nминус 1: {a_centered_sp/4}')


Первый вектор скалярного произведения : [-1.  0.  1.  1. -1.]

Второй вектор скалярного произведения : [-2.4 -0.4  2.6  1.6 -1.4]

Скалярное произведение столбцов матрицы a_centered : 8.0

Скалярное произведение столбцов матрицы a_centered
поделнное на количество измерений N (кол-во строк матрицы a)
минус 1: 2.0


#### * Задание 4
##### Число, которое мы получили в конце задания 3 является 
##### ковариацией двух признаков, содержащихся в массиве а.
##### В задании 3 мы делили сумму произведений центрированных 
##### признаков на N-1, а не на N, поэтому полученная нами величина 
##### является несмещенной оценкой ковариации.
##### В этом задании проверьте получившееся число, вычислив
##### ковариацию еще одним способом - с помощью функции np.cov.
##### В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
##### В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
##### ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [16]:
a_transponse = a.transpose()
cov = np.cov(a_transponse)
print(f'\nТранспонированная матрица a : \n{a_transponse}')
print(f'\nКовариационная матрица : \n{cov}')
print(f'\nИскомое значение ковариации : \n{cov[0,1]}')


Транспонированная матрица a : 
[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]

Ковариационная матрица : 
[[1.  2. ]
 [2.  4.3]]

Искомое значение ковариации : 
2.0
